import React from 'react';
import Head from 'next/head';
import { GetServerSideProps, NextPage } from 'next';
import Weather from '../components/weather';
import ExchangeRate from '../components/exchangeRate';
import { Symbol } from '../components/models/symbol';

interface Props {
  data: {
    symbols: Symbol[]
  }
}

const HomePage: NextPage<Props> = ({ data }) => {

  const { symbols } = data;

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='m-3 lg:flex'>
        <div className='lg:w-1/2 mx-1 border-b border-blue-600 lg:border-b-0 '>
          <Weather />
        </div>
        <div className='lg:w-1/2 mx-1' >
          <ExchangeRate symbols={symbols} />
        </div>
      </main>
    </>
  )
}

// This gets called on every request
export const getServerSideProps: GetServerSideProps = async (context) => {

  // Fetch data from external API
  var requestOptions: RequestInit | undefined = {
    method: 'GET',
  };
  const response = await fetch(`https://api.exchangerate.host/symbols`, requestOptions);
  const data = await response.json();

  // Pass data to the page via props
  return {
    props: {
      data: {
        symbols: Object.keys(data.symbols).map(item => (data.symbols[item]))
      }
    }
  }
}

export default HomePage
